# Page settings
baseurl = "localhost:1313"
title = "Agreements Network"
languageCode = "en-us"
theme = "elate"
canonifyURLs = true

[params]
  custom_css = ["css/custom.css"]

  # Meta
  author = "The Agreements Network Authors"
  description = "The legal layer for a networked world"
  email = "join@agreements.network"

  # Navigation
  [params.navigation]
    logo = "AgreementsNetwork_logo.png"
    brand = "Agreements Network"

    # home = "Home"
    overview = "Overview"
    whitepaper = "Whitepaper"
    usecases = "Use Cases"
    faq = "FAQ"
    contact = "Contact"

    # postpended links
    [[menu.postpend]]
     url = "https://docs.agreements.network/"
     name = "Docs"
     weight = 10

  # Hero section
  [params.hero]
    title = "The Agreements Network"
    subtitle = "Introducing a decentralized contract management platform that uses smart contract technology to create, prove and operate legal agreements.<br><span class='white'>It's the legal layer for a networked world.</span>"
    textureimg = "agreements-network-texture.png"

  [params.hero.video]
    enable = true
    icon = "icon-play2"
    button = "Watch the video"
    url = "https://www.youtube-nocookie.com/embed/-eMPz8D-VlA?rel=0&amp;showinfo=0&amp;controls=0&amp;autoplay=1"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "For Lawyers"
    description = "The Agreements Network is the foundation for open legal processes that will drive exponential growth in global networks."
    url = "https://www.youtube-nocookie.com/embed/kaR5JDzk0kE?rel=0&amp;showinfo=0&amp;controls=0&amp;autoplay=1"
    video = true
    button = "Watch the video"
    icon = "icon-key"
    # external = true
    # sectionLink = "usecases"
    # img = ""

  [[params.intro.item]]
    title = "For Businesses"
    description = "The Agreements Network is a powerful platform for business, reducing errors, optimizing processes, and helping control risk."
    url = "https://www.youtube-nocookie.com/embed/ypcTTjv_zbw?rel=0&amp;showinfo=0&amp;controls=0&amp;autoplay=1"
    video = true
    button = "Watch the video"
    icon = "icon-chart"
    # external = true
    # sectionLink = "usecases"
    # img = ""

  [[params.intro.item]]
    title = "For Developers"
    description = "The Agreements Network is a blockchain-based contract management platform featuring powerful smart contracts."
    url = "https://docs.agreements.network/"
    external = true
    sectionLink = ""
    button = "Read The Docs"
    icon = "icon-rocket"
    # img = ""

  # Overview section
  [params.overview]
    enable = true
    title = "Overview"

    [[params.overview.col1]]
      title = "The Problem"
      description = "Contracts are fundamental to the global economic system, yet the way agreements are formed and monitored is slow and costly. The market is failing to be effectively served by a legal establishment geared towards the bespoke and high-value. Growing markets such as the networked economy need a way to access better legal services and tools that support the way modern commerce is evolving."

    [[params.overview.col2]]
      title = "The Solution"
      description = "The Agreements Network is built to enable new and more efficient forms of operating agreements via decentralised, distributed systems. It provides a technical platform enabling lawyers to productise their previously bespoke services. It uses blockchain and smart contracts technologies to provide consumers with a real-time view on their obligations. Active Agreements on the network allow businesses to visualize their risk in a compelling way."


  # Whitepaper section
  [params.whitepaper]
    enable = true

    [[params.whitepaper.item]]
      title = "Download Our Whitepaper"
      description = "The Agreements Network is a prime opportunity to build a new legal layer in networked commerce, backed by the certainty of blockchain and smart contract-based evidence and processes. Lawyers with zero coding experience can combine their savvy, their clients’ needs and the Agreements Network to turn today’s legal problem into tomorrow’s market opportunity.<br/><br/>Read our Whitepaper to learn more about the technology and the use cases it enables."
      docimg = "AN-Whitepaper-cover.gif"

      [[params.whitepaper.item.languages]]
        button = "Read Whitepaper"
        url = "files/an_whitepaper_v1.0.pdf"

      [[params.whitepaper.item.languages]]
        button = "Leer Libro Blanco"
        url = "files/an_whitepaper_es_v1.0.pdf"

  # Use Cases section
  [params.usecases]
    enable = true
    title = "Use Cases"

    [[params.usecases.item]]
      title = "Equipment Fleet Leasing"
      subtitle = "Facilitating As-A-Service Business Models"
      description = "<p>In the evolving network economy, devices upgrade and proliferate quickly, resulting in a trend towards pay-per-use and leasing models and in deployments of fleets of equipment, for example, robotics like drones. To serve this market, agreements issues such as unit function history, ownership, payments, rights of use, maintenance and insurance may all be parameterized as workflows in the Agreements Network.</p>"
      img = "fleet-lease.png"
      alt = "Equipment Leasing - Fleets"

     [[params.usecases.item]]
      title = "Content Creators"
      subtitle = "Earning Money While Protecting Content Rights"
      description = "<p>The internet has generated profitable new media platforms for users to create and distribute content (YouTube etc). Despite the vast opportunities there are problems for creators of unique content, for example ownership of their intellectual property, ensuring fair remuneration, and protecting against third-party copyright infringement lawsuits. The Agreements Network is a powerful tool to meet these unique challenges.</p>"
      img = "agreements-network-diagram-07.png"
      alt = "Content Creators"

    [[params.usecases.item]]
      title = "Corporate Governance"
      subtitle = "Increasing Margins through Functionality and Reproducibility"
      description = "<p>Corporate governance (the rules and processes which control a company) is traditionally a meaty revenue stream for lawyers. The first stage in this essential business process is company incorporation or organization. The Agreements Network provides value by creating a persistent record of the incorporation instrument, to anchor further smart contracts for corporate governance, thus unlocking further potential legal work.</p>"
      img = "agreements-network-diagram-05.png"
      alt = "Corporate Governance"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"
    # NOTE: FAQ information is pulled from data/faq.toml

  # Involved in section
  [params.collaborators]
    enable = true
    title = "Collaborators"
    description = "Working together to launch the Agreements Network are..."
    footertext = "These companies are not in a formal legal relationship of any kind."

    [[params.collaborators.row]]
      title = "32 Advisors"
      link = "http://32advisors.com"
      img = "32_advisors.jpg"

    [[params.collaborators.row]]
      title = "Anthemis"
      link = "https://www.anthemis.com"
      img = "anthemis.jpg"

    [[params.collaborators.row]]
      title = "Erdos IP Law"
      link = "https://www.erdosiplaw.com"
      img = "erdos.jpg"

    [[params.collaborators.row]]
      title = "LegalBono"
      link = "https://www.legalbono.com"
      img = "legalbono.jpg"

    [[params.collaborators.row]]
      title = "LexPredict"
      link = "https://www.lexpredict.com"
      img = "lexpredict.jpg"

    [[params.collaborators.row]]
      title = "Monax"
      link = "https://monax.io"
      img = "monax.png"

    [[params.collaborators.row]]
      title = "Partech"
      link = "https://partechpartners.com"
      img = "partech.jpg"
      
    [[params.collaborators.row]]
      title = "Rymedi"
      link = "https://www.rymedi.com"
      img = "rymedi.jpg"
      
  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Connect With The Ecosystem"
    description = "The founders of The Agreements Network would love for you to join our growing ecosystem. Feel free to connect with us below to understand a bit more about the opportunities to join the ecosystem."

    subtitle = "Get In Touch"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-envelope", "<a href='https://lists.agreements.network' alt='https://lists.agreements.network'>mailing lists</a>"],
        ["icon-speech", "<a href='https://t.me/Agreements_Network' target='_blank'>telegram</a>"],
      ]

    # Form labels
    fname = "First Name"
    lname = "Last Name"
    email = "Email"
    button = "Subscribe To Updates"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; The Agreements Network Authors 2018. All Rights Reserved.'
